name: crawl_sticker
description: Crawling indicator for highlighting the selected list item
version: 1.2.0
homepage: https://github.com/innerwilds/crawl_sticker
repository: https://github.com/innerwilds/crawl_sticker
issue_tracker: https://github.com/innerwilds/crawl_sticker/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0